### PR TITLE
Turn the shop window into a tab

### PR DESCRIPTION
**Pull request by Ablu**
Nothing fancy so far unfortunatly... But at least it now *somehow* integrates into the client.

Next steps: Open the inventory next to the shop when entering shop, make selling / buying nicer.

This Panel stuff is getting rather messy... that needs a cleaning too...

### CODE REVIEW

**Comment by bjorn** [comment]
Hmm, I think the shop should not be a sliding panel. Why did you make it one?

**Comment by Ablu** [comment]
I implemented it like discussed in #3. I think it is a good idea because it allows to view inventory and shop next to each other (allowing to sell in one window while buying in the other) while still allowing to watch your character in the center.

Why do you think it is a bad idea?

**Comment by bjorn** [comment]
Ah, showing shop and inventory next to each other is of course a good idea. I just wouldn't visually represent it as a tab, because it is temporary and can't be triggered other than by talking to an NPC. So I would show it in the same place as the tab, but with its own frame instead of having it like a tab.

**Comment by Ablu** [comment]
I thought about giving the tab icon some special background to make sure that the tab is only temporary. Would that be intuitive enough for you? If we keep it in the sidebar as tab it also allows to switch to the stats quickly to check what values you have there (or how they changed)...

I also have no idea how to visually represent a widget flying on the left over already existing tabbar...

**Comment by bjorn** [comment]
Hrm, you have a point regarding accessibility.

**Comment by Ablu** [comment]
Well I am still open for suggestions. But currently I do not understand how your idea would be better :)

Good night,

**Comment by Ablu** [comment]
Screenshot with latest commits: https://dl.dropboxusercontent.com/u/45541625/2015-03-16-195939_609x514_scrot.png

**Comment by Ablu** [comment]
I added a patch to make the status page resizable into this branch since it would otherwise give too many conflict issues.

**Pull request merged**
