### PR TITLE
Shop ui enhancements

### PR DESCRIPTION
**Pull request by Ablu**
Current state:
screenshot from 2015-07-31 21-59-57

### CODE REVIEW

**Comment by Ablu** [comment]
I also added a first version of the selling ui:
screenshot from 2015-08-01 00-51-08

I plan to move the item display of the right side to a shareable control so the shop can use the same display.

**Comment by Ablu** [comment]
I now integrated the amount display into the item icon. I think that looks better:
screenshot from 2015-08-01 17-05-11

**Comment by Ablu** [comment]
Ok now the item row is a shared control between the inventory and the shop window. This also brings the amount display into the shop window:
screenshot from 2015-08-01 17-56-18

**Comment by bjorn** [comment]
Awesome developments @Ablu!

**Comment by Ablu** [comment]
I just did a short self review and found nothing really bad code wise. If there are no further objections I would merge this for now and see what I can improve as a next step.

**Comment by bjorn** [comment]
@Ablu No objections. :-)

**Pull request merged**
